import { nanoid } from 'nanoid';
import type { Resume } from '../types';

export const defaultResume: Resume = {
  personal: {
    name: 'Shivam Soni',
    rollNumber: '24B4525',
    department: 'Industrial Engineering and Operations Research',
    degree: 'B.Tech',
    institute: 'Indian Institute of Technology Bombay',
    gender: 'Male',
    dob: '13/10/2005',
    minorNote: 'Pursuing Dual Minor in Computer Science and Artificial Intelligence & Data Science at IIT Bombay',
  },
  academics: [
    { id: nanoid(), examination: 'Graduation', university: 'IIT Bombay', institute: 'IIT Bombay', year: '2028', cpi: '9.41' },
    { id: nanoid(), examination: 'Intermediate', university: 'CBSE', institute: 'Shiv Jyoti Convent School, Kota', year: '2024', cpi: '94.8%' },
    { id: nanoid(), examination: 'Matriculation', university: 'CBSE', institute: 'Satya Prakash Public School, Jabalpur', year: '2022', cpi: '97.2%' },
  ],
  spacing: {
    sectionTop: 12,
    sectionBottom: 6,
    projectBottom: 12,
    bulletItemSep: 2,
  },
  sections: [
    {
      id: nanoid(),
      type: 'scholastic',
      displayTitle: 'Scholastic Achievements',
      color: 'blue',
      items: [
        {
          kind: 'simple_list',
          id: nanoid(),
          bullets: [
            { id: nanoid(), text: "Ranked in the **Top 0.77%** in **JEE Advanced** among **0.18 Million+** candidates across the nation", textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: "Placed in **Top 0.26%** in **JEE Mains** examination among **1.47 Million+** candidates across the nation", textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: "Awarded **1 AP** (Advanced Proficiency) and **7 AA** grades for exemplary performance in first three semesters", textlsValue: 0, textlsStatus: 'ok' },
          ],
        },
      ],
    },
    {
      id: nanoid(),
      type: 'technical_experience',
      displayTitle: 'Technical Experience',
      color: 'blue',
      items: [
        {
          kind: 'project',
          id: nanoid(),
          title: 'Junior Engineer',
          subtitle: 'SeDriCa, UMIC IITB',
          guide: 'Guide: Prof. Archak Mittal',
          date: "Jan'25 - Present",
          contextLine: 'UMIC is a specialized technical team dedicated to designing advanced autonomous ground and aerial robotic vehicles, participated in 5+ international competitions and consistently ranked among the top tiers',
          bullets: [
            { id: nanoid(), text: 'Serving in **Motion Planning** Subsystem, working on developing autonomous stack for vehicle navigation', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Developed a custom **Artificial Potential Field** local planner for real-time **high-speed racing** in F1Tenth', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Simulated and benchmarked algorithm performance on **Autodrive** and **F1TENTH** Gym ROS environments', textlsValue: 0, textlsStatus: 'ok' },
          ],
        },
        {
          kind: 'project',
          id: nanoid(),
          title: 'Full Scale Self-Driving Golf Cart',
          subtitle: 'SeDriCa x Gahan AI',
          organization: 'UMIC, IITB',
          date: "Dec'25 - Present",
          bullets: [
            { id: nanoid(), text: 'Deployed **Hybrid A*** global planner with **Reeds-Shepp curves** for smooth, **Ackermann-compliant** trajectories', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Orchestrating decision-making using **Behavior Trees** to handle complex scenarios and recovery behaviors', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Validating collision-free urban navigation in **CARLA** leveraging Reinforcement Learning and **QD** based algorithms', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Developing **AI-integrated**, safety-critical and controllable traffic simulations for robust autonomous vehicle training', textlsValue: 0, textlsStatus: 'ok' },
          ],
        },
      ],
    },
    {
      id: nanoid(),
      type: 'projects',
      displayTitle: 'Key Projects',
      color: 'blue',
      items: [
        {
          kind: 'project',
          id: nanoid(),
          title: 'Intelligent Cart Super Add-On (CSAO)',
          subtitle: 'Zomathon Data Hackathon, Eternal',
          date: "Apr'26",
          contextLine: "Secured **2nd Place Nationally** among **6,000+ participants** for building an end-to-end recommendation system suggesting real-time cart add-ons to maximise **AOV lift** and **Cart-to-Order ratio** within **200-300ms** SLA",
          bullets: [
            { id: nanoid(), text: 'Built **4**-level synthesis pipeline with **10K+** orders via **3** realism injections mirroring stochastic real-world scenarios', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Engineered a hybrid neural architecture fusing **Set Transformer** and **GRU4Rec** via cross-attention with **LightGBM**', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Designed **3**-tier cold-start strategy leveraging SLM embeddings, LLM knowledge graphs, and Bayesian priors', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Achieved ~**65ms** P99 latency (3x below SLA) via asynchronous ONNX execution and a **Redis**-backed pre-fetch layer', textlsValue: 0, textlsStatus: 'ok' },
          ],
        },
        {
          kind: 'project',
          id: nanoid(),
          title: 'Multi-Agent Investment Teaser Generator',
          subtitle: 'AI-ML Hackathon at IITB, Kelp Global',
          date: "Mar'26",
          contextLine: "Secured **1st Prize** among **400+ IITB participants** for building an autonomous multi-agent system that generates consulting-grade M&A editable pitch decks and investment teasers",
          bullets: [
            { id: nanoid(), text: 'Engineered specialized agents to autonomously scrape public web data from Google and fuse private financials', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Engineered **JSON** **schemas** prompting Gemini to autonomously orchestrate sector-adaptive slide logic and content', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Created highly interactive **Next.js** UI featuring a **Slate.js** rich-text editor and dynamic charts for seamless visualization', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Integrated **Zustand** and **PptxGenJS** to generate fully editable, brand-compliant .pptx files featuring native charts', textlsValue: 0, textlsStatus: 'ok' },
          ],
        },
        {
          kind: 'project',
          id: nanoid(),
          title: 'Autonomous Rover for Inventory Management',
          subtitle: 'Inter IIT Tech Meet 14.0',
          date: "Nov'25 - Dec'25",
          contextLine: "Secured **2nd Prize** among **23 IITs** for **Eternal** (parent company of Zomato & Blinkit) by engineering and presenting a scaleable and cost-efficient autonomous rover for inventory auditing in front of Industry professionals",
          bullets: [
            { id: nanoid(), text: 'Built a highly optimized ROS2 based pipeline, using **Cartographer** for SLAM and **SMAC** Global Planner', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Deployed LiDAR, IMU, wheel encoder and novel visual odometry based **EKF sensor fusion** for precise localization', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Designed a **Unity** based **Digital Twin** for validation and deployed **Zenoh RMW** for low-latency HMI telemetry', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Engineered Inventory Management Workflow for Rack Detection, QR decoding, OCR and Occupancy Estimation', textlsValue: 0, textlsStatus: 'ok' },
          ],
        },
        {
          kind: 'project',
          id: nanoid(),
          title: 'Community Detection in Networks',
          subtitle: 'Course Project - IE203',
          guide: 'Data Structures & Algorithms',
          date: "Oct '25 - Nov '25",
          bullets: [
            { id: nanoid(), text: 'Engineered **Fast Louvain Algorithm** reducing computational steps by **35.43%** compared to **standard Louvain**', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Modeled **tree-splitting** and **dynamic** iteration, slashing redundant **ΔQ** calculations with **O(V+E)** complexity', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Reduced runtime by **15%–30%** on large graphs via an **early stopping criterion** based on **node migration rates**', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Evaluated performance via **SNAP datasets**, parsing **81k-node** Twitter graph with **improved modularity scores**', textlsValue: 0, textlsStatus: 'ok' },
          ],
        },
        {
          kind: 'project',
          id: nanoid(),
          title: 'Deep RL for Stock Trading Optimization',
          subtitle: 'FinSearch',
          organization: 'Finance Club, IITB',
          date: "Jul'25 - Aug'25",
          bullets: [
            { id: nanoid(), text: 'Developed a Finalist-winning **Proximal Policy Optimization** based DRL agent for stock trading strategies', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Achieved **40%** return & **1.49** Sharpe Ratio over 2 year and benchmarked against **ARIMA & LSTM** models', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Built a custom stock trading environment in OpenAI Gym, implementing **drawdown-aware** reward shaping', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Developed a training pipeline with **clipped surrogate loss** and **entropy regularization** for stable PPO training', textlsValue: 0, textlsStatus: 'ok' },
          ],
        },
        {
          kind: 'project',
          id: nanoid(),
          title: 'Simulated Annealing for Combinatorial Optimization',
          subtitle: 'Course Project - IE211',
          guide: 'Prof. Urban Larsson',
          date: "Oct'25 - Nov'25",
          bullets: [
            { id: nanoid(), text: 'Developed a general-purpose Simulated Annealing **solver**, approximating solutions to **NP-hard** combinatorial problems', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Implemented **iterative reheating** and a **hybrid Quench Phase**, refining local minima for superior accuracy', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Solved **NP-Hard TSP** via 2-opt moves and **non-convex portfolio optimization** to maximize **Sharpe Ratios**', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Detected communities in social networks with **93% similarity** to **Louvain method** by optimizing modularity', textlsValue: 0, textlsStatus: 'ok' },
          ],
        },
        {
          kind: 'project',
          id: nanoid(),
          title: 'Autonomous Social Media Agent',
          subtitle: 'ArmorIQ Hackathon at IITB',
          date: "Feb'26",
          bullets: [
            { id: nanoid(), text: 'Integrated **OpenClaw**, a custom **MCP Server**, and the **Instagram Graph API** for social media management', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Fused ArmorIQ Intent Intelligence to evaluate intent and block unauthorized pre-execution actions to align with policies', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Secured A2A interactions via identity fabrics for real-time policy enforcement and compliance auditing', textlsValue: 0, textlsStatus: 'ok' },
          ],
        },
        {
          kind: 'project',
          id: nanoid(),
          title: 'Randomized Graphs',
          subtitle: 'Course Project - IE102',
          guide: 'Prof. Narayan Rangaraj & Prof. N. Hemachandra',
          date: "Apr'25",
          bullets: [
            { id: nanoid(), text: 'Analyzed **Erdős-Rényi random graphs**, studying connectivity, giant component emergence, and clustering', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Developed scripts using **NetworkX** to simulate network behavior and visualize the connectivity threshold', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Investigated real-world applications of random graph theory, including **epidemic spreading** and information cascades', textlsValue: 0, textlsStatus: 'ok' },
          ],
        },
        {
          kind: 'project',
          id: nanoid(),
          title: 'Decoding the Basket',
          subtitle: 'Stratify',
          organization: 'Analytics Club & Consult Club IITB',
          date: "Aug'25",
          bullets: [
            { id: nanoid(), text: 'Engineered behavioral features from **1.38M+ records**, extracting purchase frequency and temporal order patterns', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Performed **Market Basket Analysis** with **mlxtend**, mapping affinities via **NetworkX** for bundling strategies', textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: 'Built a collaborative filtering recommendation engine leveraging **KNN** and **cosine similarity** for business strategy', textlsValue: 0, textlsStatus: 'ok' },
          ],
        },
      ],
    },
    {
      id: nanoid(),
      type: 'skills',
      displayTitle: 'Technical Skills',
      color: 'blue',
      items: [
        {
          kind: 'table',
          id: nanoid(),
          rows: [
            { label: 'Web', content: 'Python, C/C++, JavaScript, HTML, CSS, FastAPI, Next.js, Django, React' },
            { label: 'ML & Data Science', content: 'TensorFlow, Keras, PyTorch, OpenCV, gymnasium, YOLO, NetworkX, NumPy, Pandas, SciPy, Seaborn, Matplotlib, scikit-learn, mlxtrend, Agentic AI, RAG' },
            { label: 'Software/Tools', content: 'Git, LaTeX, Docker, Arduino, ROS2, n8n, LangChain, Fusion360, Canva, Figma' },
          ],
        },
      ],
    },
    {
      id: nanoid(),
      type: 'courses',
      displayTitle: 'Key Courses',
      color: 'blue',
      items: [
        {
          kind: 'table',
          id: nanoid(),
          rows: [
            { label: 'Computer Science', content: 'Data Structures and Algorithms, Artificial Intelligence and Machine Learning, Computer Networks*, Computer Programming and Utilization, Programming & Computing Lab, Data Analytics & AI/ML Lab*, Machine Learning for Natural Language and Knowledge Graphs*, Stochastic Processes & Queueing Systems**' },
            { label: 'Mathematics', content: "Calculus, Linear Algebra, Differential Equations, Probability and Statistics, Linear Optimization and Network Flows, Estimation on Lie Groups, Nonlinear and Discrete Optimization*, Optimization Modeling Lab*, Feedbacks and Dynamics*" },
          ],
        },
      ],
    },
    {
      id: nanoid(),
      type: 'extracurricular',
      displayTitle: 'Extracurricular Activities',
      color: 'blue',
      items: [
        {
          kind: 'simple_list',
          id: nanoid(),
          bullets: [
            { id: nanoid(), text: "Mentored a high school team to **win Amazon Future Engineer**'s Solve for Society with a **Rs.30K prize** ('25)", textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: "Selected for **IDEAS** Program at IITB securing a competitive grant of **Rs.75,000** for startup ideation ('25)", textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: "Achieved an impressive **International Rank 191** in the **Science Olympiad Foundation's NCO** ('19)", textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: "Competed at **Indian Zonals** (Western Region) **Swimming** Championship organized by CBSE ('16)", textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: "Secured **Gold Medal in Aquatics** at General Championship at IITB leading Hostel 2 to victory ('24)", textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: "Attained **5th place** in **Powai Run Marathon**, organized by Brookfield Properties and E-Cell IITB ('25)", textlsValue: 0, textlsStatus: 'ok' },
            { id: nanoid(), text: "Completed **1-year NCC training** at IIT Bombay, building discipline, leadership, and teamwork ('24-'25)", textlsValue: 0, textlsStatus: 'ok' },
          ],
        },
      ],
    },
  ],
};
